# Copyright (c) 2015 Intel Corporation. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
version: 19.6.0.{build}
clone_folder: c:\projects\realsense-extensions-crosswalk\src\extensions
init:
- cmd: git config --global core.autocrlf input
environment:
  DEPOT_TOOLS_WIN_TOOLCHAIN: 0
  XWALK_CHANNEL: canary
  XWALK_VERSION: 19.49.506.0
install:
- cmd: >-
    git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git c:\projects\realsense-extensions-crosswalk\src\third_party\depot_tools

    set PATH=%PATH%;c:\projects\realsense-extensions-crosswalk\src\third_party\depot_tools

    mkdir c:\projects\xwalk

    cd c:\projects\xwalk

    curl -fsS -o crosswalk64-%XWALK_VERSION%.zip https://download.01.org/crosswalk/releases/crosswalk/windows/%XWALK_CHANNEL%/%XWALK_VERSION%/crosswalk64-%XWALK_VERSION%.zip

    set XWALK_HOME=c:\projects\xwalk\crosswalk64-%XWALK_VERSION%.zip

    npm install -g https://github.com/crosswalk-project/crosswalk-app-tools.git

    set PATH=%PATH%;C:\Program Files (x86)\WiX Toolset v3.10\bin

    cd c:\projects\realsense-extensions-crosswalk

    gclient config --spec=solutions=[{'name':'src','url':'https://github.com/crosswalk-project/crosswalk-extensions-sdk.git','deps_file':'DEPS','managed':True,'custom_deps':{'extensions/third_party/libpxc':'https://github.com/crosswalk-project/libpxc.git'},'safesync_url':'',},]

    gclient sync
before_build:
- cmd: >-
    curl -fsS -o get-pip.py https://bootstrap.pypa.io/get-pip.py

    python get-pip.py

    set PATH=%PATH%;c:\Python27\Scripts

    pip install https://closure-linter.googlecode.com/svn/trunk/

    cd c:\projects\realsense-extensions-crosswalk\src\extensions

    python ..\tools\lint.py
build_script:
- cmd: >-
    cd c:\projects\realsense-extensions-crosswalk\src

    gn gen out\Release_x64_gn --args="is_debug=false"

    ninja -C out\Release_x64_gn sample_app
after_build:
- cmd: >-
    cd c:\projects\realsense-extensions-crosswalk\src\out\Release_x64_gn

    7z a realsense_extensions.zip realsense_extensions

    appveyor PushArtifact realsense_extensions.zip

    7z a sample_installer.zip org.crosswalk_project.rs_sample_with_rssdk_runtime_*

    appveyor PushArtifact sample_installer.zip
deploy:
  description: 'Release Description'
  provider: GitHub
  auth_token:
    secure: x7Q/400f4Ng1G+6j+c70wrgd866E3lDV1buKeHZPdftRo/cog1kP3CFE612n/kP5
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag: true
test: off

artifacts:
    - path: realsense_extensions.zip
      name: RealSense Extensions for crosswalk

    - path: sample_installer.zip
      name: Sample App Installer
